### ISSUE TITLE
when list, the list doesnt show in the feed, it keeps just loading

### ISSUE THREAD

**Issue by Privatenode90** [Grape-Labs/grape-art#6]
first, awesome product. I just tried it today the problem is that 
When list an NFT, the list doesn't show up in the feed nor the selling section. Instead it keeps just loading forever. 
I tried to run it with a custom RPC, and the same issue. 
it's different then the main website grape.art

**Comment by kirksgithub** [comment]
1. Thank you for your feedback
2. yes that is correct, grape.art uses it's own auction house program, the auction house program in the repo is the default demo auction house with 0% fees for testing and any listings you do there will not show on grape.art but on your own build (do you see the NFT listed for sale on your build?)

**Comment by Privatenode90** [comment]
i waited up for an hour and nothing, it keeps loading

**Comment by kirksgithub** [comment]
What rpc endpoint are you using for transactions

**Comment by Privatenode90** [comment]
it's specified from grapetools. constants.st? 

export const FREE_RPC_ENDPOINT = process.env.REACT_APP_API_FREE_RPC_ENDPOINT || '<transaxction RPC??>';
export const GRAPE_RPC_ENDPOINT = process.env.REACT_APP_API_GRAPE_RPC_ENDPOINT || <transaxction RPC??>

**Comment by Privatenode90** [comment]
Transaction*

**Comment by kirksgithub** [comment]
in the constants.tsx file:
`export const FREE_RPC_ENDPOINT = process.env.REACT_APP_API_FREE_RPC_ENDPOINT || 'https://api.mainnet-beta.solana.com';
export const GRAPE_RPC_ENDPOINT = process.env.REACT_APP_API_GRAPE_RPC_ENDPOINT || 'https://api.mainnet-beta.solana.com';`
update only the GRAPE_RPC_ENDPOINT to your own rpc provider, for the FREE_RPC_ENDPOINT do not use an rpc provider unless you are paying for it, they have a high tendency of failing (this is to minimize botting), so you should use either:
https://api.mainnet-beta.solana.com - Solana-hosted api node cluster, backed by a load balancer; rate-limited or
https://solana-api.projectserum.com - Project Serum-hosted api node

(I will rename the FREEto be TX_RPC_ENDPOINT)

**Comment by Privatenode90** [comment]
Ok, I used a paid version, paid 299 for quick-node. i understand free version doesn't work fine )
but sill the same, will try different a provider

**Comment by Privatenode90** [comment]
The whole concept is amazing, hope can see it in action. Hope this will be fixed soon and we can view the Feed section

**Comment by kirksgithub** [comment]
latest version on here now has a new tariable TX_RPC_ENDPOINT just edit that one to use https://solana-api.projectserum.com/ from the constants file
the GRAPE_RPC_ENDPOINT should use your own endpoint (the quick-node one)

**Comment by Privatenode90** [comment]
thanks so much, that was fast "god speed"
