### ISSUE TITLE
how to connect AH 

### ISSUE THREAD

**Issue by eajacka** [Grape-Labs/grape-art#9]
Hi There,

How can I integrate my auction house, I already have an auction house account. 

Thank you

**Comment by eajacka** [comment]
is there a config file where I can plug it in?

**Comment by kirksgithub** [comment]
Thanks for your reply of course you can, where are you going to launch your version?

**Comment by eajacka** [comment]
not really yet TBH. I was just playing around with it

**Comment by kirksgithub** [comment]
auctionHouse/Helpers/constants.tsx - so you can edit the AH from that file directly
if you do deploy please let us know will be happy to see forked versions out in the wild but please note that if you do change the auction house please update and use your own logo:
utils/grapeTools/constants.tsx (we have a MARKET_LOGO and you can simply add a url there)

**Comment by eajacka** [comment]
thank you I'll keep you posted!

**Comment by kirksgithub** [comment]
absolutely, can't wait to see what you cook up ;)

**Comment by eajacka** [comment]
if you'd like to collaborate (just an idea) we can provide marketing and all that stuff to send it to the moon

**Comment by kirksgithub** [comment]
who is we???

**Comment by eajacka** [comment]
as the project is very nice! We're ninjapromo
